<a href="https://colab.research.google.com/github/qedir051/ML-Projects/blob/main/Churn_with_tf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [ ]:
df = pd.read_csv('/content/Churn.csv')

In [ ]:
df.head()

,Unnamed: 0,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Complain,Satisfaction Score,Card Type,Point Earned,Exited
0,0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,2,DIAMOND,464,Yes
1,1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,1,3,DIAMOND,456,No
2,2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,3,DIAMOND,377,Yes
3,3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,5,GOLD,350,No
4,4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,5,GOLD,425,No

In [ ]:
df.isna().sum()

Unnamed: 0            0
RowNumber             0
CustomerId            0
Surname               0
CreditScore           0
Geography             0
Gender                0
Age                   0
Tenure                0
Balance               0
NumOfProducts         0
HasCrCard             0
IsActiveMember        0
EstimatedSalary       0
Complain              0
Satisfaction Score    0
Card Type             0
Point Earned          0
Exited                0
dtype: int64

In [ ]:
df.drop(['RowNumber','CustomerId','Surname'],axis=1,inplace=True)
df["Exited"] = df["Exited"].apply(lambda x: 1 if x == "Yes" else 0)

In [ ]:
df.head()

,Unnamed: 0,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Complain,Satisfaction Score,Card Type,Point Earned,Exited
0,0,619,France,Female,42,2,0.00,1,1,1,101348.88,1,2,DIAMOND,464,1
1,1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,1,3,DIAMOND,456,0
2,2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,3,DIAMOND,377,1
3,3,699,France,Female,39,1,0.00,2,0,0,93826.63,0,5,GOLD,350,0
4,4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,5,GOLD,425,0

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('Exited', axis=1), df['Exited'], test_size=0.2, random_state=42)

In [ ]:
X_train.head()

,Unnamed: 0,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Complain,Satisfaction Score,Card Type,Point Earned
9254,9254,686,France,Male,32,6,0.00,2,1,1,179093.26,0,2,DIAMOND,510
1561,1561,632,Germany,Male,42,4,119624.60,2,1,1,195978.86,0,4,PLATINUM,959
1670,1670,559,Spain,Male,24,3,114739.92,1,1,0,85891.02,1,4,SILVER,327
6087,6087,561,France,Female,27,9,135637.00,1,1,0,153080.40,1,2,SILVER,567
6669,6669,517,France,Male,56,9,142147.32,1,0,0,39488.04,1,3,PLATINUM,727

In [ ]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

object_columns = X_train.select_dtypes(include=['object']).columns
numeric_columns = X_train.select_dtypes(include=['float64', 'int64']).columns

num_pipeline = Pipeline([
    ('scaler', StandardScaler())
])

object_pipeline = Pipeline([
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

transformer = ColumnTransformer([
        ('num', num_pipeline, numeric_columns),
        ('cat', object_pipeline, object_columns)]
)

X_train_transformed = transformer.fit_transform(X_train)
X_test_transformed = transformer.transform(X_test)

feature_names = transformer.get_feature_names_out()

X_train_transformed = pd.DataFrame(X_train_transformed, columns = feature_names)
X_test_transformed = pd.DataFrame(X_test_transformed, columns = feature_names)

X_train_transformed

,num__Unnamed: 0,num__CreditScore,num__Age,num__Tenure,num__Balance,num__NumOfProducts,num__HasCrCard,num__IsActiveMember,num__EstimatedSalary,num__Complain,...,num__Point Earned,cat__Geography_France,cat__Geography_Germany,cat__Geography_Spain,cat__Gender_Female,cat__Gender_Male,cat__Card Type_DIAMOND,cat__Card Type_GOLD,cat__Card Type_PLATINUM,cat__Card Type_SILVER
0,1.469277,0.356500,-0.655786,0.345680,-1.218471,0.808436,0.649203,0.974817,1.367670,-0.509942,...,-0.430193,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
1,-1.194994,-0.203898,0.294938,-0.348369,0.696838,0.808436,0.649203,0.974817,1.661254,-0.509942,...,1.565908,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,-1.157244,-0.961472,-1.416365,-0.695393,0.618629,-0.916688,0.649203,-1.025834,-0.252807,1.961007,...,-1.243749,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
3,0.372469,-0.940717,-1.131148,1.386753,0.953212,-0.916688,0.649203,-1.025834,0.915393,1.961007,...,-0.176791,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,0.574030,-1.397337,1.625953,1.386753,1.057449,-0.916688,-1.540351,-1.025834,-1.059600,1.961007,...,0.534515,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,0.250217,1.207474,1.435808,1.039728,-0.102301,-0.916688,0.649203,0.974817,-0.539860,-0.509942,...,-0.167899,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
7996,0.062163,0.314989,1.816097,-1.389442,-1.218471,-0.916688,0.649203,0.974817,-1.733882,-0.509942,...,0.454493,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
7997,0.131081,0.865009,-0.085351,-1.389442,-1.218471,2.533560,-1.540351,-1.025834,-0.142765,1.961007,...,0.316678,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
7998,-1.437767,0.159323,0.390011,1.039728,1.827259,-0.916688,0.649203,-1.025834,-0.050826,1.961007,...,0.325569,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
7999,0.782171,0.470655,1.150590,-1.389442,1.149720,-0.916688,0.649203,0.974817,-0.814568,-0.509942,...,0.143297,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [ ]:
X_train_transformed.shape

(8000, 21)

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=[21]),
    tf.keras.layers.Dense(300, activation='relu'),
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(2, activation='sigmoid')
])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [ ]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(X_train_transformed, y_train, epochs=10, validation_data=(X_test_transformed, y_test))

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9422 - loss: 0.1411 - val_accuracy: 0.9990 - val_loss: 0.0067
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9988 - loss: 0.0080 - val_accuracy: 0.9990 - val_loss: 0.0082
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9987 - loss: 0.0061 - val_accuracy: 0.9970 - val_loss: 0.0140
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9984 - loss: 0.0071 - val_accuracy: 0.9990 - val_loss: 0.0102
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9993 - loss: 0.0022 - val_accuracy: 0.9990 - val_loss: 0.0120
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9992 - loss: 0.0026 - val_accuracy: 0.9985 - val_loss: 0.0120
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9991 - loss: 0.0024 - val_accuracy: 0.9975 - val_loss: 0.0151
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9998 - loss: 5.0436e-04 - val_accuracy: 0.9980 - val_loss: 0.0138
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9997 - loss: 8.3910e-04 - val_accuracy: 0.9975 - val_loss: 0.0187
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 1.0000 - loss: 2.8267e-04 - val_accuracy: 0.9985 - val_loss: 0.0175